# Generated by Django 2.2.7 on 2019-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('marking', models.CharField(blank=True, max_length=30)),
                ('material_name', models.CharField(max_length=120)),
                ('unit', models.CharField(default='кг', max_length=3)),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
            options={
                'ordering': ['material_name'],
            },
        ),
    ]
