# Generated by Django 2.2.7 on 2019-11-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191120_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=20, unique=True)),
                ('b_year', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=1)),
                ('b_month', models.CharField(blank=True, editable=False, max_length=1)),
                ('b_number', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=4)),
            ],
            options={
                'ordering': ['b_year', 'b_month', 'b_number'],
            },
        ),
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_id', models.CharField(max_length=20, unique=True)),
                ('can_date', models.DateField(blank=True, editable=False)),
                ('can_time', models.TimeField(blank=True, editable=False)),
                ('can_device', models.CharField(blank=True, editable=False, max_length=3)),
                ('can_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Batch_pr')),
            ],
            options={
                'ordering': ['can_id'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=20, unique=True)),
                ('lot_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Material')),
            ],
        ),
        migrations.CreateModel(
            name='W_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_user_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lot')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Material')),
                ('weighting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Can')),
            ],
            options={
                'ordering': ['weighting_id__batch', 'material'],
            },
        ),
        migrations.AddField(
            model_name='can',
            name='can_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.W_user'),
        ),
    ]
