# Generated by Django 2.2.7 on 2019-11-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191121_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighting',
            options={'ordering': ['weighting_id__can_batch', 'material']},
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_material',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.Material'),
        ),
    ]
