# Generated by Django 2.2.7 on 2019-11-21 15:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191121_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_code',
            field=models.CharField(max_length=20, unique=True, validators=[main.models.validate_length]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Material'),
        ),
    ]
