# Generated by Django 2.2.7 on 2019-11-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191122_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_lot_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='manufacturer_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Manufacturer_lot'),
        ),
    ]
