# Generated by Django 2.2.7 on 2019-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191122_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Producer_lot',
        ),
    ]
