# Generated by Django 2.2.7 on 2019-12-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191206_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='barcode',
        ),
    ]
